/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package com.mycompany.ipc2_practica01.GUI;

import com.mycompany.ipc2_practica01.GUI.RegistrosJIF.RegistroAsistenciaJIF;
import com.mycompany.ipc2_practica01.GUI.RegistrosJIF.RegistroEventoJIF;
import com.mycompany.ipc2_practica01.GUI.RegistrosJIF.RegistroParticipanteJIF;

/**
 *
 * @author jgarcia07
 */
public class RegistrosJIFrame extends javax.swing.JInternalFrame {

    /**
     * Creates new form RegistrosJIFrame
     */
    public RegistrosJIFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MenuRegistro = new javax.swing.JDesktopPane();
        btn_REvento = new javax.swing.JButton();
        btn_RParticipante = new javax.swing.JButton();
        btn_Actividad = new javax.swing.JButton();
        btn_Asistencia = new javax.swing.JButton();

        MenuRegistro.setBackground(new java.awt.Color(51, 51, 51));

        btn_REvento.setText("Registrar Evento");
        btn_REvento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_REventoActionPerformed(evt);
            }
        });

        btn_RParticipante.setText("Registar Participante");
        btn_RParticipante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_RParticipanteActionPerformed(evt);
            }
        });

        btn_Actividad.setText("Registrar Actividad ");
        btn_Actividad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ActividadActionPerformed(evt);
            }
        });

        btn_Asistencia.setText("Registrar Asistencia");
        btn_Asistencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_AsistenciaActionPerformed(evt);
            }
        });

        MenuRegistro.setLayer(btn_REvento, javax.swing.JLayeredPane.DEFAULT_LAYER);
        MenuRegistro.setLayer(btn_RParticipante, javax.swing.JLayeredPane.DEFAULT_LAYER);
        MenuRegistro.setLayer(btn_Actividad, javax.swing.JLayeredPane.DEFAULT_LAYER);
        MenuRegistro.setLayer(btn_Asistencia, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout MenuRegistroLayout = new javax.swing.GroupLayout(MenuRegistro);
        MenuRegistro.setLayout(MenuRegistroLayout);
        MenuRegistroLayout.setHorizontalGroup(
            MenuRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MenuRegistroLayout.createSequentialGroup()
                .addContainerGap(414, Short.MAX_VALUE)
                .addGroup(MenuRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_Asistencia, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_Actividad, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_RParticipante)
                    .addComponent(btn_REvento, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(369, 369, 369))
        );
        MenuRegistroLayout.setVerticalGroup(
            MenuRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuRegistroLayout.createSequentialGroup()
                .addGap(84, 84, 84)
                .addComponent(btn_REvento)
                .addGap(45, 45, 45)
                .addComponent(btn_RParticipante)
                .addGap(47, 47, 47)
                .addComponent(btn_Actividad)
                .addGap(49, 49, 49)
                .addComponent(btn_Asistencia)
                .addContainerGap(357, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MenuRegistro)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MenuRegistro)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_ActividadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ActividadActionPerformed
        //RegistroActividad RActividad = new RegistroActividad();
        
    }//GEN-LAST:event_btn_ActividadActionPerformed

    private void btn_AsistenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_AsistenciaActionPerformed
        RegistroAsistenciaJIF RAsistencia = new RegistroAsistenciaJIF();
        MenuRegistro.add(RAsistencia);
        RAsistencia.setVisible(true);
    }//GEN-LAST:event_btn_AsistenciaActionPerformed

    private void btn_REventoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_REventoActionPerformed
        RegistroEventoJIF REvento = new RegistroEventoJIF();
        MenuRegistro.add(REvento);
        REvento.setVisible(true);
    }//GEN-LAST:event_btn_REventoActionPerformed

    private void btn_RParticipanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_RParticipanteActionPerformed
        RegistroParticipanteJIF RParticipante = new RegistroParticipanteJIF();
        MenuRegistro.add(RParticipante);
        RParticipante.setVisible(true);
    }//GEN-LAST:event_btn_RParticipanteActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane MenuRegistro;
    private javax.swing.JButton btn_Actividad;
    private javax.swing.JButton btn_Asistencia;
    private javax.swing.JButton btn_REvento;
    private javax.swing.JButton btn_RParticipante;
    // End of variables declaration//GEN-END:variables
}
