/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package com.mycompany.ipc2_practica01.GUI;

import com.mycompany.ipc2_practica01.BDconnection.BDconnection;
import javax.swing.JOptionPane;

/**
 *
 * @author jgarcia07
 */
public class ReportesJIFrame extends javax.swing.JInternalFrame {

    private BDconnection con = new BDconnection();
    /**
     * Creates new form ReportesJIFrame
     */
    public ReportesJIFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btn_ReporteParticipantes = new javax.swing.JButton();
        btn_ReporteActividad = new javax.swing.JButton();
        btn_ReporteEvento = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(51, 51, 51));

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setForeground(new java.awt.Color(51, 51, 51));

        btn_ReporteParticipantes.setText("Reporte de Participantes");
        btn_ReporteParticipantes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ReporteParticipantesActionPerformed(evt);
            }
        });

        btn_ReporteActividad.setText("Reporte de Actividades");
        btn_ReporteActividad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ReporteActividadActionPerformed(evt);
            }
        });

        btn_ReporteEvento.setText("Reporte de Eventos");
        btn_ReporteEvento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ReporteEventoActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Liberation Sans", 0, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Emitir Reporte");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(339, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btn_ReporteParticipantes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_ReporteActividad, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_ReporteEvento, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(365, 365, 365))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(313, 313, 313))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(jLabel1)
                .addGap(76, 76, 76)
                .addComponent(btn_ReporteParticipantes)
                .addGap(38, 38, 38)
                .addComponent(btn_ReporteActividad)
                .addGap(39, 39, 39)
                .addComponent(btn_ReporteEvento)
                .addContainerGap(345, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

   private void mensajeQuery(int respuesta){
       if(respuesta == 0){
           JOptionPane.showMessageDialog(null, "Reporte Creado Correctamente");
       } else {
           JOptionPane.showMessageDialog(null, "Ha Ocurrido un Error al Crear el Reporte");
       }
   }
    
    private void btn_ReporteParticipantesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ReporteParticipantesActionPerformed
        con.connect();
        mensajeQuery(con.reporteParticipantes());
    }//GEN-LAST:event_btn_ReporteParticipantesActionPerformed

    private void btn_ReporteActividadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ReporteActividadActionPerformed
        con.connect();
        mensajeQuery(con.reporteActividades());
    }//GEN-LAST:event_btn_ReporteActividadActionPerformed

    private void btn_ReporteEventoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ReporteEventoActionPerformed
        con.connect();
        mensajeQuery(con.reporteEventos());
    }//GEN-LAST:event_btn_ReporteEventoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_ReporteActividad;
    private javax.swing.JButton btn_ReporteEvento;
    private javax.swing.JButton btn_ReporteParticipantes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
