/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.ipc2_practica01.GUI;

/**
 *
 * @author jgarcia07
 */
public class TriForceEvents extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TriForceEvents.class.getName());

    /**
     * Creates new form TriForceEvents
     */
    public TriForceEvents() {
        initComponents();
        this.setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelOpciones = new javax.swing.JPanel();
        btn_Registros = new javax.swing.JButton();
        btn_Inscripcion = new javax.swing.JButton();
        btn_Reportes = new javax.swing.JButton();
        btn_Pagos = new javax.swing.JButton();
        btn_Certificado = new javax.swing.JButton();
        btn_validarInscripcion = new javax.swing.JButton();
        btn_subirArchivo = new javax.swing.JButton();
        MenuPrincipal = new javax.swing.JDesktopPane();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setName("TriForceEvents"); // NOI18N

        panelOpciones.setBackground(new java.awt.Color(51, 51, 51));
        panelOpciones.setForeground(new java.awt.Color(255, 255, 255));

        btn_Registros.setText("Registros");
        btn_Registros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_RegistrosActionPerformed(evt);
            }
        });

        btn_Inscripcion.setText("Inscripcion");
        btn_Inscripcion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_InscripcionActionPerformed(evt);
            }
        });

        btn_Reportes.setText("Reportes");
        btn_Reportes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ReportesActionPerformed(evt);
            }
        });

        btn_Pagos.setText("Pagos ");
        btn_Pagos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_PagosActionPerformed(evt);
            }
        });

        btn_Certificado.setText("Certificado");
        btn_Certificado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_CertificadoActionPerformed(evt);
            }
        });

        btn_validarInscripcion.setText("Validar Inscrip.");
        btn_validarInscripcion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_validarInscripcionActionPerformed(evt);
            }
        });

        btn_subirArchivo.setText("Subir Archivo");
        btn_subirArchivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_subirArchivoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelOpcionesLayout = new javax.swing.GroupLayout(panelOpciones);
        panelOpciones.setLayout(panelOpcionesLayout);
        panelOpcionesLayout.setHorizontalGroup(
            panelOpcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelOpcionesLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(panelOpcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btn_validarInscripcion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_Reportes, javax.swing.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE)
                    .addComponent(btn_Registros, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_Inscripcion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_Pagos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_Certificado, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE)
                    .addComponent(btn_subirArchivo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(39, Short.MAX_VALUE))
        );
        panelOpcionesLayout.setVerticalGroup(
            panelOpcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelOpcionesLayout.createSequentialGroup()
                .addGap(166, 166, 166)
                .addComponent(btn_subirArchivo, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_Registros, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_Pagos, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_Inscripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_validarInscripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_Certificado, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_Reportes, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(165, Short.MAX_VALUE))
        );

        MenuPrincipal.setBackground(new java.awt.Color(0, 0, 0));

        jLabel1.setFont(new java.awt.Font("Nimbus Mono PS", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("TriForce");

        jLabel2.setFont(new java.awt.Font("Nimbus Mono PS", 0, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Events");

        MenuPrincipal.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        MenuPrincipal.setLayer(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout MenuPrincipalLayout = new javax.swing.GroupLayout(MenuPrincipal);
        MenuPrincipal.setLayout(MenuPrincipalLayout);
        MenuPrincipalLayout.setHorizontalGroup(
            MenuPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuPrincipalLayout.createSequentialGroup()
                .addContainerGap(417, Short.MAX_VALUE)
                .addGroup(MenuPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MenuPrincipalLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(355, 355, 355))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MenuPrincipalLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(330, 330, 330))))
        );
        MenuPrincipalLayout.setVerticalGroup(
            MenuPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuPrincipalLayout.createSequentialGroup()
                .addGap(277, 277, 277)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelOpciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(MenuPrincipal)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelOpciones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(MenuPrincipal)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_RegistrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_RegistrosActionPerformed
        RegistrosJIFrame registros = new RegistrosJIFrame();
        MenuPrincipal.add(registros);
        registros.setVisible(true);
    }//GEN-LAST:event_btn_RegistrosActionPerformed

    private void btn_InscripcionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_InscripcionActionPerformed
        InscripcionJIFrame inscripcion = new InscripcionJIFrame();
        MenuPrincipal.add(inscripcion);
        inscripcion.setVisible(true);
    }//GEN-LAST:event_btn_InscripcionActionPerformed

    private void btn_ReportesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ReportesActionPerformed
        ReportesJIFrame reporte = new ReportesJIFrame();
        MenuPrincipal.add(reporte);
        reporte.setVisible(true);
    }//GEN-LAST:event_btn_ReportesActionPerformed

    private void btn_PagosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_PagosActionPerformed
        PagosJIFrame pagos = new PagosJIFrame();
        MenuPrincipal.add(pagos);
        pagos.setVisible(true);
    }//GEN-LAST:event_btn_PagosActionPerformed

    private void btn_CertificadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_CertificadoActionPerformed
        CertificadoJIFrame certificado = new CertificadoJIFrame();
        MenuPrincipal.add(certificado);
        certificado.setVisible(true);
    }//GEN-LAST:event_btn_CertificadoActionPerformed

    private void btn_validarInscripcionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_validarInscripcionActionPerformed
        ValidarInscripcionJIFrame validarInscrip = new ValidarInscripcionJIFrame();
        MenuPrincipal.add(validarInscrip);
        validarInscrip.setVisible(true);
    }//GEN-LAST:event_btn_validarInscripcionActionPerformed

    private void btn_subirArchivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_subirArchivoActionPerformed
        archivoEntradaJIFrame archivo = new archivoEntradaJIFrame();
        MenuPrincipal.add(archivo);
        archivo.setVisible(true);
    }//GEN-LAST:event_btn_subirArchivoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new TriForceEvents().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane MenuPrincipal;
    private javax.swing.JButton btn_Certificado;
    private javax.swing.JButton btn_Inscripcion;
    private javax.swing.JButton btn_Pagos;
    private javax.swing.JButton btn_Registros;
    private javax.swing.JButton btn_Reportes;
    private javax.swing.JButton btn_subirArchivo;
    private javax.swing.JButton btn_validarInscripcion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel panelOpciones;
    // End of variables declaration//GEN-END:variables
}
